"""Shared JSON schema for parsing itscope marketplace `raw_json` payloads.

Used by both the dim_product_marketplace and fact_marketplace_price_snapshot
jobs so the two stay in sync when the source JSON shape evolves.
"""

from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    LongType,
    DoubleType,
    BooleanType,
    ArrayType,
)

SUPPLIER_ITEM_SCHEMA = StructType([
    StructField("id", LongType()),
    StructField("ean", StringType()),
    StructField("manufacturerSKU", StringType()),
    StructField("supplierSKU", StringType()),
    StructField("supplierId", LongType()),
    StructField("supplierName", StringType()),
    StructField("manufacturerName", StringType()),
    StructField("productName", StringType()),
    StructField("longDescription", StringType()),
    StructField("conditionId", LongType()),
    StructField("conditionName", StringType()),
    StructField("eolProduct", BooleanType()),
    StructField("matchQuality", LongType()),
    StructField("eanValid", BooleanType()),
    StructField("specialOffer", BooleanType()),
    StructField("price", DoubleType()),
    StructField("priceCalc", DoubleType()),
    StructField("currencyCode", StringType()),
    StructField("priceCalcVat", DoubleType()),
    StructField("priceLastUpdate", StringType()),
    StructField("stockSupplierText", StringType()),
    StructField("stockStatus", LongType()),
    StructField("stockStatusText", StringType()),
    StructField("stock", LongType()),
    StructField("externalStock", LongType()),
    StructField("stockAvailabilityDate", StringType()),
    StructField("lastStockUpdate", StringType()),
    StructField("contractTypeId", LongType()),
    StructField("contractTypeName", StringType()),
    StructField("grossDimX", DoubleType()),
    StructField("grossDimY", DoubleType()),
    StructField("grossDimZ", DoubleType()),
    StructField("recommendedRetailPriceNet", DoubleType()),
])

ITSCOPE_PRODUCT_SCHEMA = StructType([
    StructField("puid", LongType()),
    StructField("ean", StringType()),
    StructField("manufacturerSKU", StringType()),
    StructField("icecatId", StringType()),
    StructField("eClass", StringType()),
    StructField("eClassV7", StringType()),
    StructField("UNSPSC", StringType()),
    StructField("manufacturerId", LongType()),
    StructField("manufacturerName", StringType()),
    StructField("productName", StringType()),
    StructField("shortDescription", StringType()),
    StructField("longDescription", StringType()),
    StructField("productTypeId", LongType()),
    StructField("productTypeGroupId", StringType()),
    StructField("productTypeGroupName", StringType()),
    StructField("productTypeName", StringType()),
    StructField("attributeTypeId1", LongType()),
    StructField("attributeTypeName1", StringType()),
    StructField("attributeTypeId2", LongType()),
    StructField("attributeTypeName2", StringType()),
    StructField("attributeTypeId3", LongType()),
    StructField("attributeTypeName3", StringType()),
    StructField("attributeTypeId4", LongType()),
    StructField("attributeTypeName4", StringType()),
    StructField("attributeTypeId5", LongType()),
    StructField("attributeTypeName5", StringType()),
    StructField("attributeValue1", StringType()),
    StructField("productSubTypeId", StringType()),
    StructField("productSubType", StringType()),
    StructField("colorFamilyId", StringType()),
    StructField("colorFamily", StringType()),
    StructField("estimateGrossWeight", DoubleType()),
    StructField("valueAddedTaxGermany", LongType()),
    StructField("deeplink", StringType()),
    StructField("standardHtmlDatasheet", StringType()),
    StructField("standardPdfDatasheet", StringType()),
    StructField("htmlSpecs", StringType()),
    StructField("entryDate", StringType()),
    StructField("rank", LongType()),
    StructField("qualification", LongType()),
    StructField("recommendedRetailPriceNet", DoubleType()),
    StructField("price", DoubleType()),
    StructField("priceCalc", DoubleType()),
    StructField("currencyCode", StringType()),
    StructField("priceCalcVat", DoubleType()),
    StructField("priceLastUpdate", StringType()),
    StructField("priceSupplierId", LongType()),
    StructField("priceSupplierName", StringType()),
    StructField("priceSupplierItemId", LongType()),
    StructField("priceSupplierSKU", StringType()),
    StructField("stockSupplierText", StringType()),
    StructField("stockStatus", LongType()),
    StructField("stockStatusText", StringType()),
    StructField("stock", LongType()),
    StructField("stockLastUpdate", StringType()),
    StructField("aggregatedStatus", LongType()),
    StructField("aggregatedStatusText", StringType()),
    StructField("aggregatedStock", LongType()),
    StructField("aggregatedSupplierItems", LongType()),
    StructField("contractTypeId", LongType()),
    StructField("contractTypeName", StringType()),
    StructField("supplierItems", ArrayType(SUPPLIER_ITEM_SCHEMA)),
])
